### ISSUE TITLE
Total links to process: 0

### ISSUE THREAD

**Issue by jmacina** [serpapi/clauneck#4]
Can't seem to get the links to process. 

Serp API collects the webpages correctly.

Also informing the URL directly gives me the same error.

I always get the same output: "Total links to process: 0"

Checked on Serpapi and the API call goes through correctly with information being returned normally.

Example:
`clauneck --api_key KEYREDACTED --output results.csv --q "intitle:dentist AND inurl:/contact OR inurl:/contact-us miami"`

**Comment by kagermanov27** [comment]
@jmacina Thanks for your feedback.

Google is serving fewer and fewer cached page results in their SERP. We have implemented a solution to recreate a web-cache link in [v0.0.3](https://rubygems.org/gems/clauneck).

The problem is resolved now in the latest version:
```
Using SerpApi to collect webpages...
Total links to process: 199
```
